# Generated by roxyassert: do not edit by hand.
# Re-generated on devtools::document(). Commit this file like NAMESPACE.

assert_args_FredSeries__initialize <- function(api_key, base_url, async, max_tries, throttle_rate) {
  assert_scalar_character(api_key)
  assert_scalar_character(base_url)
  assert_scalar_logical(async)
  assert_scalar_count(max_tries)
  assert_between(max_tries, lower = 1)
  if (!is.null(throttle_rate)) {
    assert_scalar_double(throttle_rate)
    assert_between(throttle_rate, lower = 0, lower_inclusive = FALSE, upper = Inf, upper_inclusive = FALSE)
  }
  return(invisible(NULL))
}

assert_return_FredSeries__initialize <- function(value) {
  assert_class(value, "FredSeries")
  return(value)
}

assert_args_FredSeries__get_series <- function(series_id, observation_start, observation_end, realtime_start, realtime_end, units, frequency, aggregation_method, sort_order, limit, offset) {
  assert_scalar_character(series_id)
  if (!is.null(observation_start)) {
    assert_scalar_character(observation_start)
  }
  if (!is.null(observation_end)) {
    assert_scalar_character(observation_end)
  }
  if (!is.null(realtime_start)) {
    assert_scalar_character(realtime_start)
  }
  if (!is.null(realtime_end)) {
    assert_scalar_character(realtime_end)
  }
  if (!is.null(units)) {
    assert_scalar_character(units)
  }
  if (!is.null(frequency)) {
    assert_scalar_character(frequency)
  }
  if (!is.null(aggregation_method)) {
    assert_scalar_character(aggregation_method)
  }
  assert_scalar_character(sort_order)
  assert_value_in_set(sort_order, c("asc", "desc"))
  if (!is.null(limit)) {
    assert_scalar_count(limit)
    assert_between(limit, lower = 1)
  }
  if (!is.null(offset)) {
    assert_scalar_count(offset)
    assert_between(offset, lower = 0)
  }
  return(invisible(NULL))
}

assert_return_FredSeries__get_series <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("series_id", "date", "value", "realtime_start", "realtime_end"))
  assert_character(value[["series_id"]])
  assert_no_missing_values(value[["series_id"]])
  assert_date(value[["date"]])
  assert_no_missing_values(value[["date"]])
  assert_double(value[["value"]])
  assert_date(value[["realtime_start"]])
  assert_no_missing_values(value[["realtime_start"]])
  assert_date(value[["realtime_end"]])
  assert_no_missing_values(value[["realtime_end"]])
  return(value)
}

assert_args_FredSeries__get_series_vintages <- function(series_id, realtime_start, realtime_end, page_limit) {
  assert_scalar_character(series_id)
  assert_scalar_character(realtime_start)
  assert_scalar_character(realtime_end)
  assert_scalar_count(page_limit)
  assert_between(page_limit, lower = 1)
  return(invisible(NULL))
}

assert_return_FredSeries__get_series_vintages <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("series_id", "date", "value", "realtime_start", "realtime_end"))
  assert_character(value[["series_id"]])
  assert_no_missing_values(value[["series_id"]])
  assert_date(value[["date"]])
  assert_no_missing_values(value[["date"]])
  assert_double(value[["value"]])
  assert_date(value[["realtime_start"]])
  assert_no_missing_values(value[["realtime_start"]])
  assert_date(value[["realtime_end"]])
  assert_no_missing_values(value[["realtime_end"]])
  return(value)
}

assert_args_FredSeries__get_series_info <- function(series_id, realtime_start, realtime_end) {
  assert_scalar_character(series_id)
  if (!is.null(realtime_start)) {
    assert_scalar_character(realtime_start)
  }
  if (!is.null(realtime_end)) {
    assert_scalar_character(realtime_end)
  }
  return(invisible(NULL))
}

assert_return_FredSeries__get_series_info <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("series_id", "title", "observation_start", "observation_end", "frequency", "frequency_short", "units", "units_short", "seasonal_adjustment", "seasonal_adjustment_short", "last_updated", "last_updated_raw", "popularity", "group_popularity", "notes", "realtime_start", "realtime_end"))
  assert_character(value[["series_id"]])
  assert_no_missing_values(value[["series_id"]])
  assert_character(value[["title"]])
  assert_no_missing_values(value[["title"]])
  assert_date(value[["observation_start"]])
  assert_no_missing_values(value[["observation_start"]])
  assert_date(value[["observation_end"]])
  assert_no_missing_values(value[["observation_end"]])
  assert_character(value[["frequency"]])
  assert_no_missing_values(value[["frequency"]])
  assert_character(value[["frequency_short"]])
  assert_no_missing_values(value[["frequency_short"]])
  assert_character(value[["units"]])
  assert_no_missing_values(value[["units"]])
  assert_character(value[["units_short"]])
  assert_no_missing_values(value[["units_short"]])
  assert_character(value[["seasonal_adjustment"]])
  assert_no_missing_values(value[["seasonal_adjustment"]])
  assert_character(value[["seasonal_adjustment_short"]])
  assert_no_missing_values(value[["seasonal_adjustment_short"]])
  assert_datetime(value[["last_updated"]])
  assert_character(value[["last_updated_raw"]])
  assert_integer(value[["popularity"]])
  assert_integer(value[["group_popularity"]])
  assert_character(value[["notes"]])
  assert_date(value[["realtime_start"]])
  assert_no_missing_values(value[["realtime_start"]])
  assert_date(value[["realtime_end"]])
  assert_no_missing_values(value[["realtime_end"]])
  return(value)
}

assert_args_FredSeries__search_series <- function(search_text, search_type, limit, order_by, sort_order, realtime_start, realtime_end) {
  assert_scalar_character(search_text)
  assert_scalar_character(search_type)
  assert_scalar_count(limit)
  assert_between(limit, lower = 1)
  if (!is.null(order_by)) {
    assert_scalar_character(order_by)
  }
  if (!is.null(sort_order)) {
    assert_scalar_character(sort_order)
    assert_value_in_set(sort_order, c("asc", "desc"))
  }
  if (!is.null(realtime_start)) {
    assert_scalar_character(realtime_start)
  }
  if (!is.null(realtime_end)) {
    assert_scalar_character(realtime_end)
  }
  return(invisible(NULL))
}

assert_return_FredSeries__search_series <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("series_id", "title", "observation_start", "observation_end", "frequency", "frequency_short", "units", "units_short", "seasonal_adjustment", "seasonal_adjustment_short", "last_updated", "last_updated_raw", "popularity", "group_popularity", "notes", "realtime_start", "realtime_end"))
  assert_character(value[["series_id"]])
  assert_no_missing_values(value[["series_id"]])
  assert_character(value[["title"]])
  assert_no_missing_values(value[["title"]])
  assert_date(value[["observation_start"]])
  assert_no_missing_values(value[["observation_start"]])
  assert_date(value[["observation_end"]])
  assert_no_missing_values(value[["observation_end"]])
  assert_character(value[["frequency"]])
  assert_no_missing_values(value[["frequency"]])
  assert_character(value[["frequency_short"]])
  assert_no_missing_values(value[["frequency_short"]])
  assert_character(value[["units"]])
  assert_no_missing_values(value[["units"]])
  assert_character(value[["units_short"]])
  assert_no_missing_values(value[["units_short"]])
  assert_character(value[["seasonal_adjustment"]])
  assert_no_missing_values(value[["seasonal_adjustment"]])
  assert_character(value[["seasonal_adjustment_short"]])
  assert_no_missing_values(value[["seasonal_adjustment_short"]])
  assert_datetime(value[["last_updated"]])
  assert_character(value[["last_updated_raw"]])
  assert_integer(value[["popularity"]])
  assert_integer(value[["group_popularity"]])
  assert_character(value[["notes"]])
  assert_date(value[["realtime_start"]])
  assert_no_missing_values(value[["realtime_start"]])
  assert_date(value[["realtime_end"]])
  assert_no_missing_values(value[["realtime_end"]])
  return(value)
}

assert_args_FredSeries__get_releases <- function(realtime_start, realtime_end, limit, offset, order_by, sort_order) {
  if (!is.null(realtime_start)) {
    assert_scalar_character(realtime_start)
  }
  if (!is.null(realtime_end)) {
    assert_scalar_character(realtime_end)
  }
  assert_scalar_count(limit)
  assert_between(limit, lower = 1)
  if (!is.null(offset)) {
    assert_scalar_count(offset)
    assert_between(offset, lower = 0)
  }
  if (!is.null(order_by)) {
    assert_scalar_character(order_by)
  }
  if (!is.null(sort_order)) {
    assert_scalar_character(sort_order)
    assert_value_in_set(sort_order, c("asc", "desc"))
  }
  return(invisible(NULL))
}

assert_return_FredSeries__get_releases <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("release_id", "name", "press_release", "link", "notes", "realtime_start", "realtime_end"))
  assert_integer(value[["release_id"]])
  assert_no_missing_values(value[["release_id"]])
  assert_character(value[["name"]])
  assert_no_missing_values(value[["name"]])
  assert_logical(value[["press_release"]])
  assert_no_missing_values(value[["press_release"]])
  assert_character(value[["link"]])
  assert_character(value[["notes"]])
  assert_date(value[["realtime_start"]])
  assert_no_missing_values(value[["realtime_start"]])
  assert_date(value[["realtime_end"]])
  assert_no_missing_values(value[["realtime_end"]])
  return(value)
}

assert_args_FredSeries__get_release_dates <- function(release_id, realtime_start, realtime_end, limit, offset, sort_order, include_empty) {
  assert_scalar_count(release_id)
  assert_between(release_id, lower = 1)
  if (!is.null(realtime_start)) {
    assert_scalar_character(realtime_start)
  }
  if (!is.null(realtime_end)) {
    assert_scalar_character(realtime_end)
  }
  if (!is.null(limit)) {
    assert_scalar_count(limit)
    assert_between(limit, lower = 1)
  }
  if (!is.null(offset)) {
    assert_scalar_count(offset)
    assert_between(offset, lower = 0)
  }
  if (!is.null(sort_order)) {
    assert_scalar_character(sort_order)
    assert_value_in_set(sort_order, c("asc", "desc"))
  }
  assert_scalar_logical(include_empty)
  return(invisible(NULL))
}

assert_return_FredSeries__get_release_dates <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("release_id", "date"))
  assert_integer(value[["release_id"]])
  assert_no_missing_values(value[["release_id"]])
  assert_date(value[["date"]])
  assert_no_missing_values(value[["date"]])
  return(value)
}

assert_args_fred_base_url <- function(url) {
  assert_scalar_character(url)
  return(invisible(NULL))
}

assert_return_fred_base_url <- function(value) {
  assert_scalar_character(value)
  return(value)
}

assert_return_fred_api_key <- function(value) {
  assert_scalar_character(value)
  return(value)
}

assert_return_empty_dt_fred_observations <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("series_id", "date", "value", "realtime_start", "realtime_end"))
  assert_character(value[["series_id"]])
  assert_no_missing_values(value[["series_id"]])
  assert_date(value[["date"]])
  assert_no_missing_values(value[["date"]])
  assert_double(value[["value"]])
  assert_date(value[["realtime_start"]])
  assert_no_missing_values(value[["realtime_start"]])
  assert_date(value[["realtime_end"]])
  assert_no_missing_values(value[["realtime_end"]])
  return(value)
}

assert_return_empty_dt_fred_vintages <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("series_id", "date", "value", "realtime_start", "realtime_end"))
  assert_character(value[["series_id"]])
  assert_no_missing_values(value[["series_id"]])
  assert_date(value[["date"]])
  assert_no_missing_values(value[["date"]])
  assert_double(value[["value"]])
  assert_date(value[["realtime_start"]])
  assert_no_missing_values(value[["realtime_start"]])
  assert_date(value[["realtime_end"]])
  assert_no_missing_values(value[["realtime_end"]])
  return(value)
}

assert_return_empty_dt_fred_series_info <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("series_id", "title", "observation_start", "observation_end", "frequency", "frequency_short", "units", "units_short", "seasonal_adjustment", "seasonal_adjustment_short", "last_updated", "last_updated_raw", "popularity", "group_popularity", "notes", "realtime_start", "realtime_end"))
  assert_character(value[["series_id"]])
  assert_no_missing_values(value[["series_id"]])
  assert_character(value[["title"]])
  assert_no_missing_values(value[["title"]])
  assert_date(value[["observation_start"]])
  assert_no_missing_values(value[["observation_start"]])
  assert_date(value[["observation_end"]])
  assert_no_missing_values(value[["observation_end"]])
  assert_character(value[["frequency"]])
  assert_no_missing_values(value[["frequency"]])
  assert_character(value[["frequency_short"]])
  assert_no_missing_values(value[["frequency_short"]])
  assert_character(value[["units"]])
  assert_no_missing_values(value[["units"]])
  assert_character(value[["units_short"]])
  assert_no_missing_values(value[["units_short"]])
  assert_character(value[["seasonal_adjustment"]])
  assert_no_missing_values(value[["seasonal_adjustment"]])
  assert_character(value[["seasonal_adjustment_short"]])
  assert_no_missing_values(value[["seasonal_adjustment_short"]])
  assert_datetime(value[["last_updated"]])
  assert_character(value[["last_updated_raw"]])
  assert_integer(value[["popularity"]])
  assert_integer(value[["group_popularity"]])
  assert_character(value[["notes"]])
  assert_date(value[["realtime_start"]])
  assert_no_missing_values(value[["realtime_start"]])
  assert_date(value[["realtime_end"]])
  assert_no_missing_values(value[["realtime_end"]])
  return(value)
}

assert_return_empty_dt_fred_releases <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("release_id", "name", "press_release", "link", "notes", "realtime_start", "realtime_end"))
  assert_integer(value[["release_id"]])
  assert_no_missing_values(value[["release_id"]])
  assert_character(value[["name"]])
  assert_no_missing_values(value[["name"]])
  assert_logical(value[["press_release"]])
  assert_no_missing_values(value[["press_release"]])
  assert_character(value[["link"]])
  assert_character(value[["notes"]])
  assert_date(value[["realtime_start"]])
  assert_no_missing_values(value[["realtime_start"]])
  assert_date(value[["realtime_end"]])
  assert_no_missing_values(value[["realtime_end"]])
  return(value)
}

assert_return_empty_dt_fred_release_dates <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("release_id", "date"))
  assert_integer(value[["release_id"]])
  assert_no_missing_values(value[["release_id"]])
  assert_date(value[["date"]])
  assert_no_missing_values(value[["date"]])
  return(value)
}

assert_args_fred_sign_key <- function(req, keys) {
  assert_class(req, "httr2_request")
  assert_list(keys)
  return(invisible(NULL))
}

assert_return_fred_sign_key <- function(value) {
  assert_class(value, "httr2_request")
  return(value)
}

assert_args_parse_fred_response <- function(resp) {
  assert_class(resp, "httr2_response")
  return(invisible(NULL))
}

assert_return_parse_fred_response <- function(value) {
  if (!is.null(value)) {
    assert_list(value)
  }
  return(value)
}

